alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias la='ls -a'
alias ll='ls -lh'
alias lla='ls -lah'
alias ducks='du -hcsx * | sort -nr'
alias config='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'
alias gam="/home/naveg/bin/gam/gam"
alias o='/home/naveg/Alloy/alloy/ore'
alias oc='o c'
alias gclean='git branch | grep -v "^*" | grep -v "^master$" | fzf -m | xargs git branch -D'
