alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias la='ls -a'
alias ll='ls -lh'
alias lla='ls -lah'
alias ducks='du -hcsx * | sort -nr'
alias config='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'
